export const GET_HOME_MANUFACTURERS_LIST = "GET_HOME_MANUFACTURERS_LIST";
export const HOME_MANUFACTURERS_LOAD_MORE = "HOME_MANUFACTURERS_LOAD_MORE";
export const GET_HOME_MANUFACTURERS_LIST_SUB_TYPE = "GET_HOME_MANUFACTURERS_LIST_SUB_TYPE";
export const HOME_MANUFACTURERS_CLEAR_LIST = "HOME_MANUFACTURERS_CLEAR_LIST";

export const GET_MODELS_LIST_BY_HOME_MANUFACTURER = "GET_MODELS_LIST_BY_HOME_MANUFACTURER";
export const HOME_MODELS_LOAD_MORE = "HOME_MODELS_LOAD_MORE";
export const MODELS_LIST_BY_HOME_MANUFACTURER_CLEAR = "MODELS_LIST_BY_HOME_MANUFACTURER_CLEAR";
export const GET_MODELS_LIST_BY_HOME_MANUFACTURER_SEARCHED = "GET_MODELS_LIST_BY_HOME_MANUFACTURER_SEARCHED";

export const GET_ENGINES_LIST_BY_HOME_MANUFACTURER = "GET_ENGINES_LIST_BY_HOME_MANUFACTURER";
export const HOME_ENGINES_LOAD_MORE = "HOME_ENGINES_LOAD_MORE";
export const ENGINES_LIST_BY_HOME_MANUFACTURER_CLEAR = "ENGINES_LIST_BY_HOME_MANUFACTURER_CLEAR";
export const GET_ENGINES_LIST_BY_HOME_MANUFACTURER_SEARCHED = "GET_ENGINES_LIST_BY_HOME_MANUFACTURER_SEARCHED";
export const ENGINE_DETAILED_DATA_BY_HOME_SEARCH = "ENGINE_DETAILED_DATA_BY_HOME_SEARCH";
export const ENGINE_DETAILED_DATA_CLEAR = "ENGINE_DETAILED_DATA_CLEAR";

export const GET_MANUAL_SEARCH_SUBMIT_BY_ENGINE_DATA = "GET_MANUAL_SEARCH_SUBMIT_BY_ENGINE_DATA";
export const MANUAL_SEARCH_SUBMIT_LOADER = "MANUAL_SEARCH_SUBMIT_LOADER";
export const GET_MANUAL_SEARCH_SUBMIT_BY_ENGINE_DATA_LOAD_MORE = "GET_MANUAL_SEARCH_SUBMIT_BY_ENGINE_DATA_LOAD_MORE";
export const MANUAL_SEARCH_SUBMIT_LOAD_MORE_LOADER = "MANUAL_SEARCH_SUBMIT_LOAD_MORE_LOADER";
export const MANUAL_SEARCH_SUBMIT_BY_ENGINE_DATA_CLEAR = "MANUAL_SEARCH_SUBMIT_BY_ENGINE_DATA_CLEAR";

export const GET_ARTICLES_DATA_LIST = "GET_ARTICLES_DATA_LIST";
export const ARTICLES_DATA_LIST_CLEAR = "ARTICLES_DATA_LIST_CLEAR";
export const ARTICLES_DATA_LIST_LOADER = "ARTICLES_DATA_LIST_LOADER";

export const GET_ARTICLES_VIEW_DATA = "GET_ARTICLES_VIEW_DATA";
export const ARTICLES_VIEW_DATA_CLEAR = "ARTICLES_VIEW_DATA_CLEAR";
export const ARTICLES_VIEW_DATA_LOADER = "ARTICLES_VIEW_DATA_LOADER";

export const GET_PLATE_NUMBER_DATA = "GET_PLATE_NUMBER_DATA";
export const PLATE_NUMBER_DATA_LOADER = "PLATE_NUMBER_DATA_LOADER";
export const PLATE_NUMBER_DATA_CLEAR = "PLATE_NUMBER_DATA_CLEAR";
export const ENGINES_LIST_BY_PLATE_NUMBER_MORE_DATA = "ENGINES_LIST_BY_PLATE_NUMBER_MORE_DATA";
export const ENGINES_LIST_BY_PLATE_NUMBER_MORE_DATA_LOADER = "ENGINES_LIST_BY_PLATE_NUMBER_MORE_DATA_LOADER";
export const ENGINES_LIST_BY_PLATE_NUMBER_DATA_CLEAR = "ENGINES_LIST_BY_PLATE_NUMBER_DATA_CLEAR";
export const ENGINE_DETAILED_DATA_BY_PLATE_NUMBER = "ENGINE_DETAILED_DATA_BY_PLATE_NUMBER";
export const VIP_SEARCH_SUBMIT_BY_ENGINE_PLATE_NUMBER_DATA = "VIP_SEARCH_SUBMIT_BY_ENGINE_PLATE_NUMBER_DATA";
export const VIP_SEARCH_SUBMIT_BY_ENGINE_PLATE_NUMBER_DATA_CLEAR = "VIP_SEARCH_SUBMIT_BY_ENGINE_PLATE_NUMBER_DATA_CLEAR";
export const ENGINE_DETAILED_DATA_PLATE_NUMBER_CLEAR = "ENGINE_DETAILED_DATA_PLATE_NUMBER_CLEAR";

export const GET_BRAND_SEARCH_DATA = "GET_BRAND_SEARCH_DATA";
export const BRAND_SEARCH_DATA_LOAD_MORE = "BRAND_SEARCH_DATA_LOAD_MORE";
export const BRAND_SEARCH_DATA_LOAD_MORE_LOADER = "BRAND_SEARCH_DATA_LOAD_MORE_LOADER";
export const BRAND_SEARCH_SUBMIT_LOADER = "BRAND_SEARCH_SUBMIT_LOADER";
export const BRAND_SEARCH_DATA_CLEAR = "BRAND_SEARCH_DATA_CLEAR";

export const GET_PRODUCT_GROUP_SEARCH_DATA = "GET_PRODUCT_GROUP_SEARCH_DATA";
export const PRODUCT_GROUP_SEARCH_DATA_LOAD_MORE = "PRODUCT_GROUP_SEARCH_DATA_LOAD_MORE";
export const PRODUCT_GROUP_SEARCH_DATA_LOAD_MORE_LOADER = "PRODUCT_GROUP_SEARCH_DATA_LOAD_MORE_LOADER";
export const PRODUCT_GROUP_SEARCH_SUBMIT_LOADER = "PRODUCT_GROUP_SEARCH_SUBMIT_LOADER";
export const PRODUCT_GROUP_SEARCH_DATA_CLEAR = "PRODUCT_GROUP_SEARCH_DATA_CLEAR";

export const GET_BRAND_SUBMIT_ARTICLES_DATA = "GET_BRAND_SUBMIT_ARTICLES_DATA";
export const BRAND_SUBMIT_ARTICLES_SUBMIT_LOADER = "BRAND_SUBMIT_ARTICLES_SUBMIT_LOADER";
export const BRAND_SUBMIT_ARTICLES_DATA_CLEAR = "BRAND_SUBMIT_ARTICLES_DATA_CLEAR";

// --------------------------------------------------------------




